name: prod

services:
  photon.tihlde.org:
    container_name: photon.tihlde.org
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true
    restart: unless-stopped
    ports:
      - "${BIND_ADDRESS:-127.0.0.1}:4000:4000"
    env_file:
      - ".env"
    extra_hosts: # Trengs for at docker containeren skal nå redis på host
      - "host.docker.internal:host-gateway"
