name: prod

services:
  photon.tihlde.org:
    container_name: photon.tihlde.org
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true
    restart: unless-stopped
    ports:
      - "192.168.0.6:4000:4000" # Binder til LAN IP s책 Drifts Grafana-instans kan koble seg p책 fra en annen lokal IP -Borgar
    env_file:
      - ".env"
    extra_hosts: # Trengs for at docker containeren skal n책 redis p책 host
      - "host.docker.internal:host-gateway"

  photon_minio:
    image: minio/minio:latest
    container_name: photon_minio
    restart: unless-stopped
    ports:
      - "192.168.0.6:9000:9000"
      - "192.168.0.6:9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  minio_data:
