name: prod

services:
  photon.tihlde.org:
    container_name: photon.tihlde.org
    build:
      context: .
      dockerfile: apps/api/Dockerfile
      no_cache: true
    restart: unless-stopped
    ports:
      - "192.168.0.6:4000:4000" # Binder til LAN IP s책 Drifts Grafana-instans kan koble seg p책 fra en annen lokal IP -Borgar
    env_file:
      - ".env"
    extra_hosts: # Trengs for at docker containeren skal n책 redis p책 host
      - "host.docker.internal:host-gateway"
